import { CustomizationValues } from "../validation";

export const SLEEK_CUSTOMIZATION: CustomizationValues = {
  bulletIcon: "\\faAngleRight",
  color: "0.25, 0.5, 0.75",
  margin: "0.4in",
  lineSpacing: "1.0",
  sectionSpacing: "0pt",
  itemSpacing: "2pt",
  fontSize: "10pt",
  wordSpacing: "3pt",
  sectionOrder: [
    "experience",
    "projects",
    "skills",
    "education",
    "achievements",
    "por",
    "certifications",
    "extracurriculars",
    "customsections",
  ],
  sectionTitles: {
    education: "Education",
    achievements: "Achievements",
    experience: "Experience",
    projects: "Projects",
    skills: "Skills",
    por: "Positions of Responsibility",
    certifications: "Certifications",
    extracurriculars: "Extra Curriculars",
  },
};

export const PROFESSIONAL_CUSTOMIZATION: CustomizationValues = {
  bulletIcon: "\\textbullet",
  color: "0.50, 0.50, 0.50",
  margin: "0.1in",
  lineSpacing: "1.0",
  sectionSpacing: "0pt",
  itemSpacing: "0pt",
  fontSize: "10pt",
  wordSpacing: "3pt",
  sectionOrder: [
    "experience",
    "projects",
    "education",
    "skills",
    "achievements",
    "por",
    "certifications",
    "extracurriculars",
    "customsections",
  ],
  sectionTitles: {
    education: "Education",
    achievements: "Achievements",
    experience: "Experience",
    projects: "Projects",
    skills: "Skills",
    por: "Positions of Responsibility",
    certifications: "Certifications",
    extracurriculars: "Extra Curriculars",
  },
};

export const BREEZE_CUSTOMIZATION: CustomizationValues = {
  bulletIcon: "$\\circ$",
  color: "0, 0, 0",
  margin: "0.5in",
  lineSpacing: "1.25",
  sectionSpacing: "0pt",
  itemSpacing: "2pt",
  fontSize: "10pt",
  wordSpacing: "3pt",
  sectionOrder: [
    "education",
    "experience",
    "projects",
    "skills",
    "achievements",
    "por",
    "certifications",
    "extracurriculars",
    "customsections",
  ],
  sectionTitles: {
    education: "Education",
    achievements: "Achievements",
    experience: "Experience",
    projects: "Projects",
    skills: "Skills",
    por: "Positions of Responsibility",
    certifications: "Certifications",
    extracurriculars: "Extra Curriculars",
  },
};
export const MINIMALIST_CUSTOMIZATION: CustomizationValues = {
  bulletIcon: "\\tiny$\\bullet$",
  color: "0.25, 0.5, 0.75",
  margin: "0.4in",
  lineSpacing: "1.25",
  sectionSpacing: "0pt",
  itemSpacing: "2pt",
  fontSize: "10pt",
  wordSpacing: "3pt",
  sectionOrder: [
    "education",
    "experience",
    "projects",
    "por",
    "skills",
    "achievements",
    "certifications",
    "extracurriculars",
    "customsections",
  ],
  sectionTitles: {
    education: "Education",
    achievements: "Achievements",
    experience: "Experience",
    projects: "Projects",
    skills: "Skills",
    por: "Positions of Responsibility",
    certifications: "Certifications",
    extracurriculars: "Extra Curriculars",
  },
};

export const SLATE_CUSTOMIZATION: CustomizationValues = {
  bulletIcon: "\\tiny$\\bullet$",
  color: "0, 0.5, 0",
  margin: "0.4in",
  lineSpacing: "1.0",
  sectionSpacing: "0pt",
  itemSpacing: "2pt",
  fontSize: "11pt",
  wordSpacing: "3pt",
  sectionOrder: [
    "skills",
    "experience",
    "education",
    "projects",
    "por",
    "achievements",
    "certifications",
    "extracurriculars",
    "customsections",
  ],
  sectionTitles: {
    education: "Education",
    achievements: "Achievements",
    experience: "Experience",
    projects: "Projects",
    skills: "Skills",
    por: "Positions of Responsibility",
    certifications: "Certifications",
    extracurriculars: "Extra Curriculars",
  },
};
export const IMPACTPRO_CUSTOMIZATION: CustomizationValues = {
  bulletIcon: "\\textbullet",
  color: "0.50, 0.50, 0.50",
  margin: "0.2in",
  lineSpacing: "1.0",
  sectionSpacing: "0pt",
  itemSpacing: "1pt",
  fontSize: "10pt",
  wordSpacing: "3pt",
  sectionOrder: [
    "education",
    "achievements",
    "experience",
    "projects",
    "skills",
    "por",
    "certifications",
    "extracurriculars",
    "customsections",
  ],
  sectionTitles: {
    education: "Education",
    achievements: "Achievements",
    experience: "Experience",
    projects: "Projects",
    skills: "Skills",
    por: "Positions of Responsibility",
    certifications: "Certifications",
    extracurriculars: "Extra Curriculars",
  },
};
export const STACKED_CUSTOMIZATION: CustomizationValues = {
  bulletIcon: "$\\circ$",
  color: "20,105,170",
  margin: "0.7in",
  lineSpacing: "1.1",
  sectionSpacing: "0pt",
  itemSpacing: "0pt",
  fontSize: "10pt",
  wordSpacing: "5pt",
  sectionOrder: [
    "skills",
    "experience",
    "education",
    "projects",
    "por",
    "achievements",
    "certifications",
    "extracurriculars",
    "customsections",
  ],
  sectionTitles: {
    education: "Education",
    achievements: "Achievements",
    experience: "Experience",
    projects: "Projects",
    skills: "Skills",
    por: "Positions of Responsibility",
    certifications: "Certifications",
    extracurriculars: "Extra Curriculars",
  },
};
